import { create_ssr_component, validate_component } from 'svelte/internal';
import { Cayo, Entry } from 'cayo';

/* src/pages/index.svelte generated by Svelte v3.49.0 */

const Pages = create_ssr_component(($$result, $$props, $$bindings, slots) => {
	return `<h1>Cayo Project</h1>
${validate_component(Cayo, "Cayo").$$render($$result, { src: "counter.cayo.svelte" }, {}, {})}
${validate_component(Entry, "Entry").$$render($$result, { src: "index.js" }, {}, {})}`;
});

export { Pages as default };
