import path from 'path';

// Generate runtime helper that finds and parses a component instance's prop data
export function generateGetProps() {
  return (
`
function getProps(cayoElement) {
  const json = cayoElement.dataset.cayoProps;
  return JSON.parse(json);
}
`
  );
}

export function generateCayoRuntime(components, fileName, _cayo) {
  const { config, __VERSION__ } = _cayo;
  let code = '';
  let instances = '';
  // Add banner
  code += `/* ${fileName} generated by Cayo v${__VERSION__} */\n`;
  
  if (Object.keys(components).length !== 0) {
    // TODO: add this path to config (internal only)
    const componentPathBase = path.resolve(config.cayoPath, './__cayo/components');
    Object.entries(components).forEach(([name, ids]) => {
      // Add component dependency import
      code += `import ${name} from '${componentPathBase}/${name}.svelte.js';\n`;
      // Generate component instances
      ids.forEach(id => {
        instances += generateComponentInstance(id, name)
      });
    });
    
    // Add getProps (used by component instances)
    code += generateGetProps();
  } else {
    instances += `  // No cayo component instances found in page HTML`;
  }

  // Add main render, which runs the component instantiations
  code += generateRender(instances);

  return { code };
}

function generateRender(contents) {
  return (
`
export default function render(cb) {
  var target = cb ? cb : (node) => node;
  let cayos = {};
${contents}
  return cayos;
}
`
  );
}

// Generate the code to wrap component instances in an event listener wrapper
export function generateComponentInstanceWrapper(contents) {
  return (
`
document.addEventListener('DOMContentLoaded', function() {
${contents}
});
`
  );
}

// Generate the code for a component instance
export function generateComponentInstance(cayoId, componentName) {
  return (
` 
  cayos['${cayoId}'] = {};
  cayos['${cayoId}'].target = document.querySelector('[data-cayo-id="${cayoId}"]');
  cayos['${cayoId}'].instance = new ${componentName}({
    target: target(cayos['${cayoId}'].target),
    hydrate: true,
    props: getProps(cayos['${cayoId}'].target),
  });
`
  );
}