import { create_ssr_component } from 'svelte/internal';

/* src/__template.svelte generated by Svelte v3.49.0 */

const _template = create_ssr_component(($$result, $$props, $$bindings, slots) => {
	return `<!-- <!DOCTYPE html> -->
<html lang="${"en"}">
  <head>
    <meta charset="${"UTF-8"}">
    <link rel="${"icon"}" href="${"/favicon.ico"}">
    <meta name="${"viewport"}" content="${"width=device-width, initial-scale=1.0"}">
    %cayo.title%
    %cayo.css%    
    %cayo.head%
  </head>
  <body>
    %cayo.body%
    %cayo.script%
  </body>
</html>`;
});

export { _template as default };
